Creating models
mihrab34/micro-reddit pull request #1
Opened 2020-06-15 21:31 UTC by mihrab34

This branch is for building models with Active record

2020-06-16 17:34 UTC, mosaaleb requested changes
#### Well done @mihrab34 :clap:

You have done most of the requirements for this project, still, there are some requirements needs to be handled before moving on:

- [ ] Linter is not set up for this repo, Let's add GitHub action and rubocop config file and make sure that we don't have any linting error. Check [this](https://github.com/microverseinc/linters-config/tree/master/ror) out.

- [ ] Take a look at my comments below

Please handle these requirements and submit a new code review.


##### Muhammad Ebeid

2020-06-16 17:34 UTC, mosaaleb commented on app/models/user.rb
> +  validates :user_name, unique: true, presence: true,
- [ ] This line gives error, it's `uniqueness: true` not unique. Please check this out: [uniqueness_validation](https://guides.rubyonrails.org/active_record_validations.html#uniqueness)

2020-06-16 17:34 UTC, mosaaleb commented on app/models/user.rb
> +  has_many :posts
- [ ] To get a user comments, we need `has_many :comments` association

2020-06-16 17:34 UTC, mosaaleb commented on app/models/comment.rb
> +  belongs_to :user, :post
- [ ] We can't write multiple belongs to in the same line. This syntax raises an error in the console
      Please separate them: 

      ```ruby
      belongs_to :user
      belongs_to :post
      ```

2020-06-18 12:07 UTC, nikasulo approved these changes
# Great work! @mihrab34 
Please merge and keep moving forward, I wish you the very best and see you at the top 🚀

2020-06-18 12:26 UTC, merged